app/daa/atlas/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url

urlpatterns = patterns('daa.atlas.views',
    (r'^$', 'index'),
    (r'^about/$', 'about'),
    (r'^help/$', 'help'),
    (r'^downloads/$', 'downloads'),
    (r'^contact/$', 'contact'),
    (r'^results/$', 'results'),
    (r'^anatomical/$', 'anatomical'),
    (r'^change/(?P<identifier>DAA\d+)/$', 'change'),
    (r'^gene/(?P<entrez_id>\d+)/$', 'gene'),
    (r'^tissue/(?P<evid>\d+)/$', 'tissue'),
    (r'^reference/(?P<id>\d+)/$', 'reference'),
    (r'^saved/(?P<method>\w+)/$', 'saved'),
    (r'^json/$', 'return_as_json'),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

app/daa/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    url(r'^$', 'daa.atlas.views.index', name='home'),
    url(r'^atlas/', include('daa.atlas.urls')),
    url(r'^tools/', include('daa.tools.urls')),
    url(r'^goterms/', include('daa.go_db.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin_tools/', include('admin_tools.urls')),
	url(r'^admin/', include(admin.site.urls)),
    url(r'^bibliography/', include('daa.django_libage.urls', namespace='libage')),
	url(r'^external/submissions/', include('daa.submissions.urls')),
)

app/daa/atlas/models.py
import datetime
import re

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils.safestring import mark_safe
from django.utils import timezone

from mptt.models import MPTTModel, TreeForeignKey
from daa.django_libage.models import Citation

class GOTerm(models.Model):
    CATEGORIES = (
        ('process', 'process'),
        ('function', 'function'),
        ('component', 'component'),
    )

    id = models.PositiveIntegerField(primary_key=True)
    term = models.CharField(max_length=50)
    category = models.CharField(max_length=20, choices=CATEGORIES)

    class Meta:
        managed = False

    def __unicode__(self):
        return str(self.id)+': '+self.term

class Organism(models.Model):
    class Meta:
        ordering = ['common_name']
        managed = False

    taxonomy_id = models.PositiveIntegerField(db_index=True)
    name = models.CharField(max_length=50)
    common_name = models.CharField(max_length=50, blank=True, null=True)
    hasDatabase = models.BooleanField()

    def __unicode__(self):
        '''
        end = ''
        if self.common_name != '':
            end = ' ('+self.common_name+')'
        return self.name+end
        '''
        if self.common_name != '':
            return self.common_name
        else:
            return self.name
    managed=False

class Homolog(models.Model):
    class Meta:
        managed = False

    symbol = models.CharField(max_length=20)
    entrez_id = models.PositiveIntegerField()

    organism = models.ForeignKey(Organism)

    def __unicode__(self):
        return self.symbol+' ('+self.organism.name+')'

def get_human_organism():
    return Organism.objects.get(taxonomy_id=9606)

class Gene(models.Model):
    class Meta:
        managed = False

    entrez_id = models.PositiveIntegerField(db_index=True)
    name = models.CharField(max_length=255, db_index=True)
    symbol = models.CharField(max_length=20, db_index=True)
    alias = models.CharField(max_length=50, blank=True, null=True, db_index=True)
    description = models.TextField(blank=True, null=True)
    omim = models.CharField(max_length=20, blank=True, null=True)
    ensembl = models.CharField(max_length=20, blank=True, null=True, db_index=True)
    uniprot = models.CharField(max_length=20, blank=True, null=True)
    unigene = models.CharField(max_length=20, blank=True, null=True)
    in_genage = models.BooleanField(default=False)

    organism = models.ForeignKey(Organism, default=get_human_organism)

    def compound_name(self):
        if self.symbol.strip() == '':
            name = self.name
        else:
            name = u'{} ({})'.format(self.symbol, self.name)
        return name

    def __unicode__(self):
        return self.symbol+' ('+self.name+')'

def generate_evid():
    try:
        last_id = Tissue.objects.order_by('evid')
        if last_id.count() > 0:
            last = last_id[last_id.count()-1]
            return last.evid+1
        else:
            return 1 
    except:
        return 0

class Tissue(MPTTModel):

    class MPTTMeta:
        order_insertion_by = ['evid']
    class Meta:
        managed = False

    evid = models.PositiveIntegerField(default=generate_evid)
    name = models.CharField(max_length=50, db_index=True)
    synonyms = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    inInterface = models.BooleanField(default=False)

    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    def __unicode__(self):
        return self.name

class PropertyGroup(models.Model):
    class Meta:
        managed = False

    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name

class Property(models.Model):
    class Meta:
        ordering = ['group']
        managed = False

    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    group = models.ForeignKey(PropertyGroup)

    def __unicode__(self):
        return self.name

class Reference(models.Model):
    class Meta:
        ordering = ['-year']
        managed = False

    pubmed = models.CharField(max_length=20, blank=True, null=True, db_index=True)
    title = models.CharField(max_length=255, blank=True, null=True, db_index=True)
    url = models.URLField(blank=True, null=True)
    author = models.CharField(max_length=100, blank=True, null=True, db_index=True)
    publisher = models.CharField(max_length=50, blank=True, null=True)
    volume = models.CharField(max_length=20, blank=True, null=True)
    pages = models.CharField(max_length=20, blank=True, null=True)
    year = models.PositiveIntegerField()
    journal = models.CharField(max_length=50, blank=True, null=True)
    editor = models.CharField(max_length=50, blank=True, null=True)
    book_title = models.CharField(max_length=255, blank=True, null=True, db_index=True)
    isbn = models.CharField(max_length=20, blank=True, null=True)

    def formatted_reference(self):
        if self.author != '':
            persons = self.author
        elif self.editor != '':
            persons = self.editor+' (editor)'
        else:
            persons = u''

        if self.pubmed != '' and self.pubmed is not None:
            link = u' (<a href="http://www.ncbi.nlm.nih.gov/pubmed/{0}">Pubmed</a>)'.format(self.pubmed)
        elif self.url != '':
            link = u' (<a href="{0}">{0}</a>)'.format(self.url)
        else:
            link = u''

        ref_format = u''
        if self.book_title != u'':
            ref_format = u'<i>{0} (editor)</i>. ({1}) {2}'.format(self.editor, str(self.year), self.book_title)
        else:
            ref_format = u'<i>{0}</i> ({1}) "{2}" <i>{3}</i> <b>{4}</b> {5} {6}'.format(persons, str(self.year), self.title, self.journal, self.volume, self.pages, link)
            
        return mark_safe(ref_format)    

    def __unicode__(self):
        if self.author != '':
            persons = self.author   
        elif self.editor != '':
            persons = self.editor+' (editor)'
        else:
            persons = ''
    
        ref_format = ''
        if self.book_title != '':
            ref_format = self.editor+' (editor). ('+str(self.year)+') '+self.book_title
        else:
            ref_format = persons+' ('+str(self.year)+') "'+self.title+'" '+self.journal+' '+self.volume+' '+self.pages
            
        return ref_format 

class Person(models.Model):
    class Meta:
        managed = False

    name = models.CharField(max_length=50)
    website = models.URLField(blank=True, null=True)
    email = models.EmailField(blank=True, null=True)

    def __unicode__(self):
        return self.name

class ProcessMeasured(models.Model):
    class Meta:
        managed = False

    name = models.CharField(max_length=100, db_index=True)

    def __unicode__(self):
        return self.name

class Data(models.Model):
    
    class Meta:
        managed = False

    TYPE = (
        ('percentage', 'Percentage Change'),
        ('equation', 'Equation'),
        ('series', 'Series'),
        ('incidence', 'Incidence Series'),
        ('morbidity', 'Morbidity Series'),
    )
    PLOT = (
        ('none', 'Do not plot'),
        ('linear', 'Linear Line'),
        ('exponential', 'Exponential Line'),
        ('line', 'Line'),
        ('bar', 'Bar'),
        ('column', 'Column'),
        ('point', 'Point'),
        ('pie', 'Pie'),
    )

    type = models.CharField(max_length=20, choices=TYPE)
    plot = models.CharField(max_length=20, choices=PLOT, default='none')
    sample_size = models.IntegerField(blank=True, null=True)
    measure = models.CharField(max_length=30, blank=True, null=True)
    method_collection = models.CharField(max_length=50, blank=True, null=True)
    data_transforms = models.CharField(max_length=50, blank=True, null=True)

    percentage_change = models.FloatField(null=True, blank=True)
    p_value = models.DecimalField(max_digits=30, decimal_places=25, blank=True, null=True)

    def get_pvalue(self):
        return self.p_value

    def __unicode__(self):
        if hasattr(self, 'percentage'):
            return self.percentage.__unicode__()
        elif hasattr(self, 'equation'):
            return self.equation.__unicode__()
        elif hasattr(self, 'dataset'):
            return self.dataset.__unicode__()
        return 'Data' 

class DataPoint(models.Model):
    class Meta:
        ordering = ['label']
        managed = False

    label = models.CharField(max_length=20)
    point = models.FloatField()

    part_of = models.ForeignKey(Data)

    def __unicode__(self):
        return self.label+' '+str(self.point)

class Percentage(Data):
    class Meta:
        managed = False

    is_negative = models.BooleanField(verbose_name="Is negative or decreases")

    def __unicode__(self):
        try:
            return self.change_set.all()[0].name
        except:
            return 'Percentage'

class Equation(Data):
    class Meta:
        managed = False

    coefficiant = models.DecimalField(max_digits=30, decimal_places=25)
    intercept = models.DecimalField(max_digits=30, decimal_places=25)

    is_negative = models.BooleanField()
    # NEED TO DEPRECATE
    p_value_d = models.DecimalField(max_digits=30, decimal_places=25, blank=True, null=True)

    def __unicode__(self):
        try:
            return self.change_set.all()[0].name
        except:
            return 'Equation'

class Dataset(Data):
    class Meta:
        managed = False

    def __unicode__(self):
        try:
            return self.change_set.all()[0].name
        except:
            return 'Dataset'
        #return 'Dataset: '+self.change_dataset.all()[0].name

class PercentageManager(models.Manager):
    class Meta:
        managed = False

    def get_query_set(self):

app/daa/atlas/templates/atlas/about.html
{% extends 'base.html' %}

{% block content %}
	
	<h1>About the Digital Ageing Atlas</h1>

	<div class="yui3-u-1-2">
		<div class="page-section">
			<h2>What is the project about?</h2>

			<p>The human ageing process is characterised by changes at different biological levels, including multiple forms of cellular and molecular damage. Our group has developed a web portal that will integrate molecular, cellular and physiological age-related data. This web portal serves as the first centralised collection of ageing changes. It will be very useful for researchers to relate age-related changes at different levels and develop new models of ageing to obtain new insights. Crucially, by having an integrated view of different age-related changes, we will be better able to understand the interplay of such changes and how they can be tackled in order to delay ageing.</p>

			<h2>Citations</h2>

			<p>If you would like to cite this resource in your papers please use the following:</p>

            <blockquote>Thomas Craig; Chris Smelick; Robi Tacutu; Daniel Wuttke; Shona H. Wood; Henry Stanley; Georges Janssens; Ekaterina Savitskaya; Alexey Moskalev; Robert Arking; Joao Pedro de Magalhaes "The Digital Ageing Atlas: integrating the diversity of age-related changes into a unified resource" Nucleic Acids Research 2014 doi: 10.1093/nar/gku843 (In Press)</blockquote>

            <p>We also have a manuscript submitted that describes the Digital Ageing Atlas. When accepted this will become the preferred way of citing this resource</p>

			<h2>Credits and Contributors</h2>

			<p>We thank the following for their contributions to the project, either technically or academically.</p>

			<ul>
				<li>João Pedro de Magalhães - Project leader</li>
				<li>Thomas Craig - Developer</li>
				<li>Chris Smelick - Compilation of physiological data for the database</li>
				<li>The Ageing Group at Liverpool University - Testing and constructive criticism</li>
			</ul>

			<h2>Become a contributor</h2>

			<p>If you would like to contribute to the database yourself, for instance if you have new data on ageing, please use the contribute page to submit your data.</p>

            <h2>Copyright and licencing</h2>

            <p class="text-centre"><a rel="license" href="http://creativecommons.org/licenses/by/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/">Creative Commons Attribution 3.0 Unported License</a>.</p>

		</div>
	</div>

	<div class="yui3-u-1-2 yui-tweak">
		<div class="page-section left-collapse">
			<h2>Sources of data</h2>

			<p>To compile the background information for the database the following sources where used:</p>

			<h3>Anatomical data</h3>

			<p>The anatomical (tissue) data was sourced from eVOContology.org (<a href="http://www.ncbi.nlm.nih.gov/pubmed/17961239">Adele Kruger, Oliver Hofmann, Piero Carninci, Yoshihide Hayashizaki and Winston Hide. Simplified ontologies allowing comparison of developmental mammalian gene expression. Genome Biology 2007, 8:R229.</a>), although this has been edited to suit the purposes of the database.</p>

			<h3>Gene details</h3>

			<p>A combination of sources where used to fetch this information. The Entrez Gene database was used to gather basic gene information, Gene Ontology terms and external links. HomoloGene was used for the gene orthologues. The NCBI Taxonomy database was used to gather the correct taxonomy information.</p>

			<h3>Bibliographic data</h3>

			<p>Bibliographic data was constructed by fetching a basic data from the NCBI PubMed database where available.</p>
			
			<h2>Technical Details</h2>

			<p>This site is built in Python, using the Django framework. It uses a PostgreSQL database for storage.</p>

			<h2>Image Credits</h2>

			<ul>
                <li><a href="http://www.flickr.com/photos/liberato/200858281/">Riga Old Man</a></li>
                <li><a href="http://www.flickr.com/photos/dark_ghetto28/407953159/">sweet old kiss</a></li>
                <li><a href="http://www.flickr.com/photos/dimsumdarren/861082870/">DNA redwoods</a></li>
                <li><a href="http://www.flickr.com/photos/jurvetson/57080968/">Riding Shotgun</a></li>
                <li><a href="http://www.flickr.com/photos/vivatier/4462185144/">Concept photo of a pet rodent in a wine glass</a></li>
                <li><a href="http://www.flickr.com/photos/beger/2348083198/">Albino Mouse</a></li>
                <li><a href="http://www.flickr.com/photos/e3000/99284256/">ssttt! little baby-mouse, sleeping on my hand</a></li>
                <li><a href="http://www.flickr.com/photos/hthg1983/2237614948/">Happy Lunar New Year of The Mouse</a></li>
			</ul>

		</div>
	</div>
		
{% endblock %}

app/daa/atlas/templates/atlas/anatomical.html
{% extends 'base.html' %}
{% load markup %}
{% load mptt_tags %}
{% load atlas_extras %}

{% block overridestyles %}
	<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.treeview.css">
{% endblock %}

{% block content %}
	
	<div class="yui3-u-1 details-header {{ change.type }}-bg">
		<h1>{{ title }}</h1>
	</div>

	<div class="yui3-u-1-3 details-column small-column">
		<div>
			<h2>Tissues</h2>
			<div>
				<h3>Filter</h2>
				<input id="filter-tissues" type="text" />
				<ul id="filter-tissues-results"></ul>
			</div>
			<div>
				<ul class="root tissue-tree treeview-blue visible">
					{% recursetree nodes %}
						<li>
                            {% with node_lookup|get_item:node.name as nodeitem %}
                            <span>{{ node.name }}</span> {% if nodeitem.number_of_changes > 0 %}<a href="{% url 'atlas.views.results' %}?l=tissue&amp;lid={{node.evid}}&amp;species[]={{active.taxonomy_id}}">{{ nodeitem.number_of_changes }} &#x27a5;</a>{% endif %}
                            {% endwith %}
							{% if not node.is_leaf_node %}
								<ul class="children">
									{{ children }}
								</ul>
							{% endif %}
						</li>
					{% endrecursetree %}
				</ul>
			</div>
		</div>
	</div>

	<div class="yui3-u-2-3 yui-tweak details-column large-column">
		<div class="no-left-margin">
			<h2>Anatomical model</h2>
            <div class="organism-choices">
                <b>Models available:</b>
                {% for s in species_available %}
                <a href="?species={{ s.taxonomy_id }}" class="button blue-button">{{ s.common_name }}</a>
                {% endfor %}
            </div>
			<div id="model">

				<div id="float-label">
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block postjs %}
<script src="{{ STATIC_URL }}js/anatomical.js"></script>
<script>
	var tissues = {{ jtissues|safe }}; 
    var species = "{{ active.common_name|lower }}";
	$(document).ready(function(){
        var url = '/static/images/svg/'+species+'.svg';
		d3.xml(url, 'image/svg+xml', function(xml) {
			$('#model').append(xml.documentElement);
		});
	})
</script>
{% endblock %}
{% block extralibs %}
	<script src="{{ STATIC_URL }}js/libs/jquery.treeview.js"></script> 
	<script src="{{ STATIC_URL }}js/libs/jquery.jscroll.min.js"></script> 
	<script src="{{ STATIC_URL }}js/libs/d3/d3.min.js"></script>
{% endblock %}

app/daa/atlas/templates/atlas/change.html
{% extends 'base.html' %}
{% load markup %}
{% load mptt_tags %}
{% load references %}
{% load markdown_deux_tags %}

{% block overridestyles %}
	<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.treeview.css">
{% endblock %}

{% block content %}
    {% if change.hide %}
    <div class="hidden-change">
        This change has been marked as hidden. It will not be displayed in the live version and may suffer from inaccuracies or lack of detail.
    </div>
    {% endif %}
	<div class="yui3-u-1 details-header {{ change.type }}-bg">
		<h1>{{ title }}</h1>
		<span class="subheading">{{ change.type|capfirst }}</span>
	</div>

	<div class="yui3-u-1-3 details-column small-column">
		<div>
			{% if change.process_measured %}
			<h2>Process Measured</h2>
			<div>{{ change.process_measured }}</div>
			{% endif %}
			{% if change.gender != 'male/female' %}
			<h2>Gender</h2>
			<div>{{ change.gender|title }}</div>
			{% endif %}
			<h2>Data Availability</h2>
			<div>
				{% if change.starts_age < 0 and change.ends_age < 0 %}
				Period at which this change occurs is not accurately known
                {% else %}
                    <span class="lowest-age">
                    {% if change.starts_age < 0 %}
                    Uknown start 
                    {% else %}
                    {{ change.starts_age }}
                    {% endif %}
                    </span>
                    to 
                    <span class="highest-age">
                    {% if change.ends_age < 0 %}
                    unknown 
                    {% else %}
                    {{ change.ends_age }}
                    {% endif %}
                    </span>
                    {{ change.time_measure }}
				{% endif %}
			</div>
			<h2>Tissue{{ change.tissues.count|pluralize }}</h2>
			<ul class="tissue-list">
			{% for tissue in change.tissues.all %}
				<li>
					<a class="tissue tissue-link" href="{% url 'atlas.views.tissue' tissue.evid %}">{{ tissue.name }}</a>
					<a href="{% url 'atlas.views.results' %}?l=tissue&amp;lid={{ tissue.evid }}" class="view-more-link">Changes</a>
					<a href="" class="button fright small show-tree">&#8681;</a>
					<ul class="root tissue-tree treeview-blue">
						{% recursetree nodes %}
							<li>
								<span {% if node.name == tissue.name %}class="current"{% endif %}>{{ node.name }}</span>
								{% if not node.is_leaf_node %}
									<ul class="children">
										{{ children }}
									</ul>
								{% endif %}
							</li>
						{% endrecursetree %}
					</ul>
				</li>
			{% endfor %}
			</ul>
			<h2>References</h2>
            {% references change.identifier %}
            {% if change.type == 'physiological' %}
            <h2>External Links</h2>
            <ul>
                <li><a href="https://www.google.com/search?site=imghp&amp;tbm=isch&amp;q={{ change.name|urlencode }}">Google image search</a></li>
            </ul>
            {% endif %}
		</div>
	</div>

	<div class="yui3-u-2-3 yui-tweak details-column large-column">
		<div class="no-left-margin">
            {% if show_add_to_saved %}
					{% if change.identifier in request.session.saved %}
						<form method="post" action="{% url 'atlas.views.saved' "remove" %}">
							{% csrf_token %}
							<input type="hidden" name="url" value="{{ request.get_full_path }}" />
							<input type="hidden" name="id" value="{{ change.identifier }}" />
							<button type="submit" class="button red-button fright button-heading">Remove from saved list</button>
						</form>
					{% else %}
						<form method="post" action="{% url 'atlas.views.saved' "add" %}">
							{% csrf_token %}
							<input type="hidden" name="url" value="{{ request.get_full_path }}" />
							<input type="hidden" name="id" value="{{ change.identifier }}" />
							<button type="submit" class="button blue-button fright button-heading">Add to saved list</button>
						</form>
					{% endif %}
				{% endif %}
			{% if change.data.percentage or change.data.equation %}

				<h2>Change</h2>
				<div>
                    {% with change.data.percentage_change|cut:"-" as value %}
					{% if change.data.percentage.is_negative or change.data.equation.is_negative %}
						<span class="negative">{% if value != '0' and value != '0.0' and value != '' and value != 'None' %}{{ change.data.percentage_change|floatformat:1|cut:"-" }}% {% endif %}Decrease</span>
					{% else %}
						<span class="positive">{% if value != '0' and value != '0.0' and value != '' and value != 'None' %}{{ change.data.percentage_change|floatformat:1|cut:"-" }}% {% endif %}Increase</span>
					{% endif %}
                    {% endwith %}
					in <span class="highlight-value">{{ change.process_measured }}</span> {% if change.data.get_pvalue %}with a P Value of <span class="highlight-value">{{ change.data.get_pvalue|stringformat:".2e" }}</span>{% endif %}
					{% if change.data.equation  %}
						<h3>Equation Details</h3>
						<table>
							<thead>
								<tr>
									<th>Equation Type</th>
									<th>Coefficient</th>
									<th>Intercept</th>
									<th>Data Transforms</th>
									<th>Method of Collection</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>{{ change.data.equation.plot }}</td>
									<td>{{ change.data.equation.coefficiant|stringformat:".2e" }}</td>
									<td>{{ change.data.equation.intercept|stringformat:".2e" }}</td>
									<td>{{ change.data.equation.data_transforms|default:"Unknown" }}</td>
									<td>{{ change.data.equation.method_collection|default:"Unknown" }}</td>
								</tr>
							</tbody>
						</table>
					{% endif %}
				</div>
			{% endif %}
			{% if change.data.dataset.datapoint_set %}
				<h2>Data</h2>
				<div id="chart"></div>
				{% with change.data.dataset as data %}
				<div class="data-table-container">
					<table>
						<thead>
							<tr>
							{% for point in data.datapoint_set.all %}
								<th>{{ point.label }}</th>
							{% endfor %}
							</tr>
						</thead>
						<tbody>
							<tr>
							{% for point in data.datapoint_set.all %}
								<td>{{ point.point }}</td>
							{% endfor %}
							</tr>
						</tbody>
					</table>
				</div>
				{% endwith %}
			{% endif %}
			{% if change.description %}
				<h2>Description</h2>
				<div>{{ change.description_with_references|markdown }}</div>
			{% endif %}
			{% if change.gene %}
				<h2>Gene</h2>
				<div>
					<a class="gene gene-link" href="{% url 'atlas.views.gene' change.gene.entrez_id %}"><b>{{ change.gene.symbol }}</b> {{ change.gene.name }}</a>
					<a href="{% url 'atlas.views.results' %}?l=gene&amp;lid={{ change.gene.entrez_id }}" class="view-more-link">Changes</a>
				</div>
			{% endif %}
			{% if rnodes %}
				<h2>Relationships</h2>
				<div class="float-fix">
				{% for nodes in rnodes %}
                    {% if forloop.counter == 1  or not forloop.counter|divisibleby:2 %}<div class="tree-row">{% endif %}
					<ul class="root rel-tree treeview-blue">
						{% recursetree nodes %}
							<li>
								{% if node.change.identifier == change.identifier %}
									<span class="current {{ node.change.type }}-type">{{ node.change.name }}</span>
								{% else %}
									<a class="{{ node.change.type }}-type" href="{% url 'atlas.views.change' node.change.identifier %}">{{ node.change.name }}</a>
								{% endif %}
								{% if not node.is_leaf_node %}
									<ul class="children">
										{{ children }}
									</ul>
								{% endif %}
							</li>
						{% endrecursetree %}
					</ul>
                    {% if forloop.counter|divisibleby:2 or foorloop.last %}
                    </div>
                    {% endif %}
				{% endfor %}
				</div>
			{% endif %}
			{% if change.properties.count > 0 %}
				<h2>Properties</h2>
				<dl>
				{% for p in change.properties.all %}
					{% ifchanged p.group %}
						</dl>
						<dl>
						<dt class="group-heading">{{ p.group }}</dt>
					{% endifchanged %}
					<dd>{{ p.name }}</dd>
				{% endfor %}
				</dl>
			{% endif %}
            {% if change.image_set.count > 0 %}
            <h2>Image gallery</h2>
            <ul class="image-gallery">
                {% for i in change.image_set.all %}
                <li>
                    <a href="{{i.image.url}}"><img src="{{ i.image.url }}"></a>
                    <span class="image-caption">{{ i.caption|markdown }}</span>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
		</div>
    </div>
{% endblock %}

{% block postjs %}
{% if change.data.dataset.datapoint_set.count > 0 %}
<script>
	var data = [{% for point in change.data.dataset.datapoint_set.all %}['{{ point.label }}', {{ point.point }}], {% endfor %}] 
	var data_measure = "{{ change.process_measured }} {{ change.data.measure }}";
</script>
{% endif %}
{% endblock %}
{% block extralibs %}
	<script src="{{ STATIC_URL }}js/libs/jquery.treeview.js"></script> 
	{% if change.data.dataset.datapoint_set.count > 0 %}
		<script src="{{ STATIC_URL }}js/libs/d3/d3.min.js"></script>
		{% if change.data.plot == 'bar' or change.data.plot == 'column' %}<script src="{{ STATIC_URL }}js/simplechart.js"></script>{% endif %}
	{% endif %}
{% endblock %}

app/daa/atlas/templates/atlas/get_querystring.html
?{% for var,value in request.GET.lists %}{% if var in keys %}{% if value|length > 1 %}{% for sv in value %}&amp;{{ var }}={{ sv }}{% endfor %}{% else %}&amp;{{ var }}={{ value|first }}{% endif %}{% endif %}{% endfor %}