app/daa/django_libage/urls.py
from django.conf.urls import patterns, include, url

import views

urlpatterns = patterns('',
    url(r'^$', views.search_references),
    url(r'^entry/(?P<identifier>\w+)/$', views.reference, name='entry'),
    url(r'^search/$', views.search_references, name='search'),
)

app/daa/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
    url(r'^$', 'daa.atlas.views.index', name='home'),
    url(r'^atlas/', include('daa.atlas.urls')),
    url(r'^tools/', include('daa.tools.urls')),
    url(r'^goterms/', include('daa.go_db.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin_tools/', include('admin_tools.urls')),
	url(r'^admin/', include(admin.site.urls)),
    url(r'^bibliography/', include('daa.django_libage.urls', namespace='libage')),
	url(r'^external/submissions/', include('daa.submissions.urls')),
)

app/daa/django_libage/models.py
import urllib

from django.db import models
from django.utils.safestring import mark_safe
from django.core.exceptions import ObjectDoesNotExist

from daa.fetchscript.fetch import FetchReference

class Source(models.Model):
    class Meta:
        db_table = 'references_source'
    name = models.CharField(max_length=200)
    short_name = models.CharField(max_length=40)
    url = models.URLField()
    base_url = models.URLField()
    colour = models.CharField(max_length=6, null=True, blank=True)
    hide = models.BooleanField(default=False)

    def get_entries(self):
        return BibliographicEntry.objects.filter(citations__source__name=self.name).distinct()

    def __unicode__(self):
        return self.name+': ('+self.url+')'

class Citation(models.Model):
    class Meta:
        unique_together = ('identifier', 'source',)
        db_table = 'references_citation'
    identifier = models.CharField(max_length=50)
    title = models.CharField(max_length=1024)
    source = models.ForeignKey(Source)
    hide = models.BooleanField(default=False)

    @property
    def citation_source(self):
        return self.source.base_url.format(self.identifier)

    def __unicode__(self):
        return self.identifier+': '+self.title

class Tag(models.Model):
    class Meta:
        db_table = 'references_tag'
    name = models.CharField(max_length=200, db_index=True)

    def get_entries(self):
        return self.bibliographicentry_set.distinct().filter(citations__source__hide=False)

    def __unicode__(self):
        return self.name

class Author(models.Model):
    class Meta:
        db_table = 'references_author'

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    initials = models.CharField(max_length=5, null=True, blank=True)

    full_name = models.CharField(max_length=250, null=True, blank=True)

    def get_full_name(self):
        return u'{} {}'.format(self.first_name, self.last_name)

    def get_search_field(self):
        encoded_name = urllib.quote_plus(self.__unicode__().encode('utf8'))
        return u'authors:"{}"'.format(encoded_name)

    def save(self, *args, **kwargs):
        self.full_name = u'{} {}'.format(self.first_name, self.last_name)
        super(Author, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'{} {}'.format(self.first_name, self.last_name)
        
class BibliographicEntryManager(models.Manager):
    """Return a BibliographicEntry instance, creating an entry if non-existant."""
    def get_or_create_from_pubmed(self, pubmed, database='libage'):
        try:
            entry = self.using(database).get(pubmed=pubmed)
        except ObjectDoesNotExist:
            fr = FetchReference()
            details = fr.fetchPubmed(pubmed, withTerms=True)
            terms = details['terms']
            authors = details['authors']
            for i in ('terms', 'author_initials', 'authors'):
                del details[i]
            entry = BibliographicEntry(**details)
            entry.save(using=database)
            for t in terms:
                tg,c = Tag.objects.using(database).get_or_create(name=t)
                entry.tags.add(tg)
            for a in authors:
                author, c = Author.objects.using(database).get_or_create(**a)
                entry.authors.add(author)
        return entry

class BibliographicEntry(models.Model):
    class Meta:
        db_table = 'references_bibliographicentry'
    pubmed = models.CharField(max_length=20, blank=True, null=True, unique=True, db_index=True)
    title = models.CharField(max_length=1024, blank=True, null=True, db_index=True)
    url = models.URLField(blank=True, null=True)
    author = models.CharField(max_length=100, blank=True, null=True, db_index=True)
    publisher = models.CharField(max_length=100, blank=True, null=True)
    volume = models.CharField(max_length=40, blank=True, null=True)
    pages = models.CharField(max_length=40, blank=True, null=True)
    year = models.PositiveIntegerField(null=True, blank=True, db_index=True, default=0)
    journal = models.CharField(max_length=100, blank=True, null=True, db_index=True)
    issue = models.CharField(max_length=40, blank=True, null=True)
    editor = models.CharField(max_length=100, blank=True, null=True, db_index=True)
    book_title = models.CharField(max_length=255, blank=True, null=True, db_index=True)
    isbn = models.CharField(max_length=20, blank=True, null=True)
    review = models.NullBooleanField()

    contact_addresses = models.CharField(max_length=200, blank=True, null=True)

    authors = models.ManyToManyField(Author)

    citations = models.ManyToManyField(Citation, blank=True, db_index=True)
    tags = models.ManyToManyField(Tag, blank=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_last_modified = models.DateTimeField(auto_now=True)

    objects = BibliographicEntryManager()

    def get_title(self):
        if self.book_title is not None and self.book_title != u'':
            return self.book_title
        return self.title

    def get_author(self):
        if (self.author == u'' or self.author is None) and (self.editor != u'' and self.editor is not None):
            return self.editor
        return self.author

    def get_short_reference(self):
        return u'{0} ({1})'.format(self.author, self.year)

    def formatted_reference(self):
        if self.author != u'' and self.author is not None:
            persons = self.author
        else:
            persons = u''

        if self.volume is not None and self.volume != u'':
            sep = ''
            if self.issue == u'' or self.issue is None:
                sep = ':'
            volume = u' <b>{vol}</b>{sep}'.format(vol=self.volume, sep=sep)
        else:
            volume = ''

        if self.issue is not None and self.issue != u'':
            issue = u"({0}):".format(self.issue)
        else:
            issue = u""

        if self.pubmed != u'' and self.pubmed is not None:
            link = u' <a class="libage-pubmed" href="http://www.ncbi.nlm.nih.gov/pubmed/{0}">(PubMed)</a>'.format(self.pubmed)
        elif self.url != '' and self.url is not None:
            link = u' (<a href="{0}">{0}</a>)'.format(self.url)
        else:
            link = u''

        if self.title != u'' and self.title is not None:
            title = u'"<b>{}</b>" '.format(self.title)
        else:
            title = u''

        if self.book_title != u'' and self.book_title is not None:
            if self.editor != u'' and self.editor is not None:
                book = u' in {editor} (Ed.) <i>{book}</i>'.format(editor=self.editor, book=self.book_title)
            book = u' in <i>{book}</i>'.format(book=self.book_title)
        else:
            book = u''

        if self.journal != u'' and self.journal is not None:
            journal = u' {}'.format(self.journal)
        else:
            journal = u''

        if self.pages != u'' and self.pages is not None:
            pages = u'{}'.format(self.pages)
        else:
            pages = u''

        if self.year != u'' and self.year is not None:
            year = u'({})'.format(self.year) 
        else:
            year = ''

        ref_format = u'{persons} {year} {title}{book}{journal}{volume}{issue}{pages}{link}'.format(persons=persons, year=year, title=title, journal=journal, volume=volume, issue=issue, pages=pages, book=book, link=link)
            
        return mark_safe(ref_format)    

    def reference(self):
        return self.__unicode__()

    def __unicode__(self):
        if self.author != u'' and self.author is not None:
            persons = u'{}'.format(self.author)
        else:
            persons = u''

        if self.volume is not None and self.volume != u'':
            sep = u''
            if self.issue == u'' or self.issue is None:
                sep = ':'
            volume = u' {vol}{sep}'.format(vol=self.volume, sep=sep)
        else:
            volume = ''

        if self.issue is not None and self.issue != u'':
            issue = u"({0}):".format(self.issue)
        else:
            issue = u""

        if self.pubmed != u'' and self.pubmed is not None:
            link = u' ({0})'.format(self.pubmed)
        elif self.url != '' and self.url is not None:
            link = u' ({0})'.format(self.url)
        else:
            link = u''

        if self.title != u'' and self.title is not None:
            title = u'"{}" '.format(self.title)
        else:
            title = u''

        if self.book_title != u'' and self.book_title is not None:
            if self.editor != u'' and self.editor is not None:
                book = u' in {editor} (Ed.) {book}'.format(editor=self.editor, book=self.book_title)
            book = u' in {book}'.format(book=self.book_title)
        else:
            book = u''

        if self.journal != u'' and self.journal is not None:
            journal = u' {}'.format(self.journal)
        else:
            journal = u''

        if self.pages != u'' and self.pages is not None:
            pages = u'{}'.format(self.pages)
        else:
            pages = u''

        if self.year != u'' and self.year is not None:
            year = u'({})'.format(self.year) 
        else:
            year = ''

        ref_format = u'{id}: {persons} {year} {title}{book}{journal}{volume}{issue}{pages}{link}'.format(id=self.id, persons=persons, year=year, title=title, journal=journal, volume=volume, issue=issue, pages=pages, book=book, link=link)

        return ref_format 

app/daa/django_libage/views.py
import json
import math
import urllib2
import urllib

from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.utils.html import strip_tags

# For native querying of the database one class needs to be imported
from daa.atlas.models import Change
from daa.atlas.tables import ChangeTable

def reference(request, identifier):
    from daa.atlas.view_functions import generate_species_options, show_sidebar
    url = '{0}/details/{1}/{2}/'.format(settings.LIBAGE_ENDPOINT, settings.LIBAGE_DATABASE, identifier)
    try:
        response = urllib2.urlopen(url).read()
    except urllib2.URLError, urllib2.HTTPError:
        response = '{}'
    results = json.loads(response)

    changes = Change.objects.select_related('data__percentage', 'data__equation', 'data__dataset', 'organism', 'process_measured', 'gene').prefetch_related('tissues', 'properties').filter(identifier__in=results['citations'])

    if request.GET.get('export') == 'True':
        export_header = ['Identifier','Change name','Change type', 'Change gender', 'Age change starts', 'Age change ends', 'Description', 'Tissues', 'Gene', 'Properties', 'Type of data', 'Process measured', 'Sample size', 'Method of collection', 'Data transforms', 'Percentage change', 'P value', 'Coefficiant', 'Intercept', 'Species']
        export_data = ""
        for e in changes:
            tissues = u", ".join([t.name.title() for t in e.tissues.all()])
            gene = e.gene.compound_name() if e.gene is not None else u""
            properties = u", ".join([prp.name for prp in e.properties.all()])
            process_measured = e.process_measured.name if e.process_measured is not None else u''
            try:
                d = e.data
                if d is not None:
                    data = {
                        'type': d.type,
                        'sample_size': d.sample_size,
                        'method_collection': d.method_collection,
                        'data_transforms': d.data_transforms,
                        'percentage_change': d.percentage_change,
                        'p_value': d.p_value,
                    }
                    try:
                        eq = d.data.equation
                        equation = {
                            'coefficiant': eq.coefficiant,
                            'intercept': eq.intercept,
                        }
                    except:
                        equation = {}
                    data.update(equation)
                else:
                    data = {}
            except ObjectDoesNotExist:
                data = {}

            tmp = u"{id}\t{name}\t{type}\t{gender}\t{start}\t{end}\t{description}\t{tissues}\t{gene}\t{properties}\t{dtype}\t{measure}\t{dsample}\t{dmethod}\t{dtransforms}\t{dpercent}\t{dpvalue}\t{dcoefficiant}\t{dintercept}\t{species}\n".format(id=e.identifier, name=e.name, type=e.type, gender=e.gender, start=e.starts_age, end=e.ends_age, description=e.description, tissues=tissues, gene=gene, properties=properties, dtype=data.get('type', ''), measure=process_measured, dsample=data.get('sample_size', ''), dmethod=data.get('method_collection', ''), dtransforms=data.get('data_transforms', ''), dpercent=data.get('percentage_change', ''), dpvalue=data.get('p_value', ''), dcoefficiant=data.get('coefficiant', ''), dintercept=data.get('intercept', ''), species=e.organism.name)
            export_data += tmp
        resp = HttpResponse(u"\t".join(export_header)+u"\n"+export_data, content_type="text/plain")
        resp['Content-Disposition'] = 'attachment; filename={}.txt'.format(strip_tags('The Digital Ageing Atlas | '+results['reference']).replace(' ', '_'))
    else:
        table = ChangeTable(changes, order_by=request.GET.get('sort'))
        table.paginate(page=request.GET.get('page', 1))
        resp = render(request, 'entry.html', {
            'title': 'The Digital Ageing Atlas | '+results['reference'],
            'ref': results['reference'], 
            'species_options': generate_species_options(request),
            'table': table,
            'libage_url': settings.LIBAGE_URL,
            'use_sidebar': True, #show_sidebar(request),
        })
    
    return resp 

def _search_count(term):
    """
    Used internally to get number of results for given term
    """
    url = '{0}/count/{1}/?q={2}'.format(settings.LIBAGE_ENDPOINT, settings.LIBAGE_DATABASE, urllib.quote(term))
    try:
        response = urllib2.urlopen(url).read()
    except:
        response = '{"count": 0, "results": []}'
    results = json.loads(response)
    return results

def search_references(request):
    q = '' if request.GET.get('s') is None else request.GET.get('s')
    sort = 'author' if request.GET.get('sort') is None else request.GET.get('sort')
    page = 1 if request.GET.get('page') is None else int(request.GET.get('page'))
    per_page = 20

    start = page-1 if page == 1 else page*per_page-1
    end = page*per_page if page == 1 else page*per_page+per_page

    url = '{0}/search/{1}/{2}/{3}/?q={4}&sort={5}'.format(settings.LIBAGE_ENDPOINT, settings.LIBAGE_DATABASE, start, end, urllib.quote(q), sort)
    try:
        response = urllib2.urlopen(url).read()
    except:
        response = '{"count": 0, "results": []}'
    results = json.loads(response)

    num_pages = int(math.ceil(results['count']/per_page))
    page_range = range(page-2 if page-2 > 0 else 1, page+3 if page+3 < num_pages else num_pages)  

    if q != '':
        title = 'Bibliography search: {0} ({1} entries)'.format(q,results['count'])
    else:
        title = 'Bibliography'
    
    return render(request, 'references.html', {
        'title': title,
        'results': results['results'],
        'count': results['count'],
        'query': q,
        'libage_url': settings.LIBAGE_URL,
        'sort': sort,
        'num_pages': num_pages,
        'page': page,
        'page_range': page_range,
        'previous': page-1 if page-1 > 1 else 1,
        'next': page+1 if page+1 < num_pages else num_pages,
    })

app/daa/django_libage/templates/entry.html
{% extends 'base.html' %}
{% load django_tables2 %}

{% block sidebar %}
    <div class="sidebar-module">
        <h2>Export results</h2>
        <p>Export the results of your search to a tab separated text file for further analysis</p>
        <form action="" method="get">
            {% for var, value in request.GET.lists %}
                {% for v in value %}
                    <input type="hidden" name="{{ var }}" value="{{v}}" />
                {% endfor %}
            {% endfor %}
            <input type="hidden" value="True" name="export" />
            <button type="submit" class="button blue-button">Export results</button>
        </form>
    </div>
{% endblock %}

{% block content %}
	
    <div class="yui3-u-1 details-header reference-bg">
        <h1>{{ ref|safe }} ({{table.paginator.count}} entries)</h1>
    </div>	

	<div class="yui3-u-1 details-column large-column">
        <div>
			<h2>Changes associated with this reference</h2>
			{% render_table table 'atlas/table.html' %}
		</div>
	</div>

{% endblock %}

app/daa/django_libage/templates/references.html
{% extends 'base.html' %}
{% load sort_buttons %}

{% block content %}
<h1>Bibliography{% if query %} search: {{query}}{% endif %} ({{count}} entries)</h1>
<div class="libage-references">
    <form method="get" action="{{ current_page_url }}" class="libage-sort-controls">
        <div class="btn-group">
            <a class="btn disabled">Sort:</a>
            {% sort_button "-citations" "Number of citations" sort %}
            {% sort_button "author" "Author" sort %}
            {% sort_button "title" "Title" sort %}
            {% sort_button "year" "Year" sort %}
        </div>
        <input type="hidden" name="s" value="{{query}}">
    </form>
    <ul class="references-list">
        {% for r in results %}
        <li class="row-fluid">
            <p class="span6">{{r.reference|safe}}</p>
            <div class="span2">
                <span class="citation-count"> 
                    <a href="{% url 'libage:entry' r.id %}"><span class="badge">{{r.current_database_citations}}</span> citation{{ r.current_database_citations|pluralize }} in this database</a>
                </span>
                {% if r.citations > 0 %}
                <br>
                <span class="citation-count"> 
                    (<a href="{{libage_url}}{{r.url}}"><span class="badge">{{r.citations}}</span> citation{{ r.citations|pluralize }} in connected databases</a>)
                </span>
                {% endif %}
            </div>
            <div class="span2">
                <a href="{{libage_url}}{{r.url}}">View in the LibAge database</a>
            </div>
            <div class="span2">
                {% if r.tags|length > 0 %}
                <ul class="tag-list row">
                    <li> 
                        <i class="icon-tags"><span class="acc-hide">Tags:</span></i>
                    </li>
                    {% for t in r.tags %}
                    {% if forloop.counter < 6 %}
                    <li><a href="{{libage_url}}{{t.url}}" class="label label-warning">{{t.name}}</a></li>
                    {% endif %}
                    {% if forloop.counter == 6 %}
                    <li><a href="{{libage_url}}{{r.url}}" class="label">More tags&hellip;</a></li>
                    {% endif %}
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="pagination">
    <ul>
        <li><a href="?page=1&amp;s={{query}}&amp;sort={{sort}}">First</a></li>
        {% if num_pages > 1 %}
            <li><a href="?page={{ previous }}&amp;s={{term}}&amp;sort={{sort}}">Previous</a></li>
        {% else %}
            <li class="disabled"><a href="?page={{page}}&amp;s={{term}}&amp;sort={{sort}}">Previous</a></li>
        {% endif %}

        {% for i in page_range %}
            {% if i == page %}
                <li class="active"><a href="?page={{i}}&amp;s={{query}}&amp;sort={{sort}}">{{i}} of {{num_pages}}</a></li>
            {% else %}
                <li><a href="?page={{i}}&amp;s={{query}}&amp;sort={{sort}}">{{i}}</a></li>
            {% endif %}
        {% endfor %}

        {% if num_pages > 1 %}
            <li><a href="?page={{ next }}&amp;s={{query}}&amp;sort={{sort}}">Next</a></li>
        {% else %}
            <li class="disabled"><a href="?page={{page}}&amp;s={{query}}&amp;sort={{sort}}">Next</a></li>
        {% endif %}
        <li><a href="?page={{num_pages}}&amp;s={{query}}&amp;sort={{sort}}">Last</a></li>
    </ul>
</div>
{% endblock %}